### ISSUE TITLE
Allow debugging without disabling output capturing

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#101]
Is there a way we can disable output capturing when a debugger runs automatically?

**Comment by CodeMouse92** [comment]
I'd almost wonder if the default should be to pipe the output by default; capture, process, and then spit it out again in some formatted fashion?

**Comment by breuleux** [comment]
The behavior of `breakpoint()` (Python >= 3.7) can be controlled with the `PYTHONBREAKPOINT` environment variable, and I believe you can modify it programmatically by setting it in `os.environ`.

It wouldn't work for e.g. explicit calls to `pdb.set_trace()`, but that's falling out of usage as people move to 3.7 and 3.8, so I think it could be a reasonable start to wrap `breakpoint` so that it turns off capture when invoked and turns it back on when execution is resumed.

**Comment by darrenburns** [comment]
That sounds like a reasonable approach. For 3.6 users we could just provide a `ward.breakpoint()` function that wraps `pdb.set_trace()`, and can be called directly.

**Comment by darrenburns** [comment]
Made a start on this a while back: https://github.com/darrenburns/ward/pull/119
