### ISSUE TITLE
Path supplied in pyproject.toml should be considered relative to project root, not current working directory

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#140]
If you supply a `path` in `pyproject.toml`, that path is considered relative to the location where you run `ward`. It should instead be considered relative to the "project root" i.e. the directory we found the `pyproject.toml` file within.

**Comment by bigsbunny** [comment]
Hey @darrenburns! I was testing the current development version of WARD, keeping this issue in mind. I created a test playground to check the functionality of pyproject.toml by providing the path to tests under [tool.ward]. 

The hierarchy of the package is :
- WARD_TESTING
	- tests/
		- test_check.py
		- test_check2.py
	- __init__.py
	- check.py #This consists of the functions to be tested
	- pyproject.toml

I also tried other varieties of arranging the files by creating further subdirectories and etc to try various combinations possible.

So the observations I made were :

- Running `ward` from 'WARD_TESTING' directory, finds and parses the 'pyproject.toml' file and follows the path provided in it to run the tests ('test_check.py' and 'test_check2.py')
- Running `ward` from 'WARD_TESTING/tests/' resulted in a path error saying `Error: Invalid value for '-p' / '--path': Path 'tests' does not exist.`. This is seemingly because it tries to find the path relative to from where I ran `ward` i.e. 'WARD_TESTING/tests/' and it doesnt' exist over there.
- Running `ward -p .` from 'WARD_TESTING/tests/' worked perfectly as according the documentation as the same path is mentioned in the 'pyproject.toml'  as well, so this one takes priority. 

I would like to work on this issue and have some doubts to be clarified.

**Comment by darrenburns** [comment]
Hey, thanks for digging into this. Yeah the issue here is what you mentioned in your second bullet point. If you write `./tests` in your config file you'd expect it to be a path from the project route. It shouldn't matter where you invoke ward from. Let me know if you have any other questions :)

**Comment by blueyed** [comment]
Just a side note: I think instead of speaking about "project root" it would be better to say that the path is relative to where it is used, i.e. the `pyproject.toml` in this case, which typically is the project root also, but I think it is still more understandable/clearer to assume it being relative to the file being used from probably.

**Comment by bigsbunny** [comment]
@darrenburns so if we have just one tests directory consisting of tests to be made, then running `ward` relative to 'pyproject.toml' or from any other point of invocation is understood. But if a project has multiple directories for various tests, then invoking `ward` from a particular tests sub-directory should imply running just the tests in that particular sub-directory right? Or should it parse 'pyproject.toml' and run all the tests mentioned in the `paths` parameter. Naturally, the former one should be the way I feel. I am asking this from a conceptual point of view and not how the code works.

**Comment by bigsbunny** [comment]
@blueyed will keep that in mind surely. Thank you!

**Comment by darrenburns** [comment]
If we find a `pyproject.toml` in the current or any parent directory, then we use the `path` specified there if none is specified via the command line. So, if you run `ward` (with no arguments) from a subdirectory, it'll look for a `pyproject.toml` in parent directories and use whatever it finds in there. It should take the path it finds inside the `pyproject.toml`, and consider it relative to the `pyproject.toml`, rather than relative to the directory you happen to be in.

**Comment by blueyed** [comment]
While I have no grasp @darrenburns's last comment fully, I'd still wanted to leave the hint that (relative) paths in `pyproject.toml` should just be relative to that file itself.
