### ISSUE TITLE
Test that ends up calling sys.exit results in "no tests found"

### ISSUE THREAD

**Issue by anlutro** [darrenburns/ward#156]
Given the following code in `test_example.py`:

```python
import sys, ward

def foo():
    sys.exit(1)

@ward.test("test foo")
def _():
    assert foo() is True
```

Running `ward` yields this output:

```
Collected 1 tests and 0 fixtures in 0.04 seconds.
NO_TESTS_FOUND in 0.04 seconds
```

Changing `foo`'s body to `return False` or `raise Exception` yields the expected error output.

**Comment by JoshKarpel** [comment]
https://github.com/darrenburns/ward/blob/85524666de8f32c9e22ea04be2d2cc794c3dfdb0/ward/testing.py#L147 could change to `except (Exception, SystemExit) as e`.

It's not immediately obvious to me that that's the right behavior though... exiting with code 0 is normally a success, so maybe catch the `SystemExit` separately and pass if it's a 0, fail otherwise? Perhaps that's too surprising...
