### ISSUE TITLE
`ward fixtures` highlighting fixtures that aren't injected into any tests

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#159]
`ward fixtures` could highlight fixtures that aren't injected into any tests. This could be disabled with a command line option.

**Comment by JoshKarpel** [comment]
Per discussion in #151 and #154 , this is harder than it sounds because `ward` doesn't look at fixtures until it runs tests, and it looks at fixtures as it goes on a test-by-test-basis. So it's reasonably clear how to do something like `ward test --show-fixture-usage`, but to do `ward fixtures --show-usage` something needs to change in the test execution workflow.

I propose looking at https://github.com/darrenburns/ward/blob/master/ward/testing.py#L135 . Dry runs abort before this code, because they don't want to resolve argument *values*, because that would involve computation. I haven't dug through the code path, but perhaps this block https://github.com/darrenburns/ward/blob/6a165fd7cc65b98629ff71d0f869f5cde00b0bab/ward/testing.py#L278 can be augmented to store off the fixture used by the test, and then (in a dry run) not actually execute the fixture.

A more drastic change, that I think makes more sense architecturally: instead of resolving arguments in that method, produce a "resolution specification" that can be evaluated later. So you produce the specification whether the run is dry or not, but only evaluate it when you actually run the test. The specification can then be consumed for meta-analysis. This might be as simple as splitting out https://github.com/darrenburns/ward/blob/6a165fd7cc65b98629ff71d0f869f5cde00b0bab/ward/testing.py#L278 and doing that check later, merely storing the non-fixture args and the fixtures themselves in the dictionary.

Happy to take a crack at this!

**Comment by darrenburns** [comment]
All of what you said aligns with my thoughts :) you're more than welcome to give it a go if you fancy it!

> A more drastic change, that I think makes more sense architecturally: instead of resolving arguments in that method, produce a "resolution specification" that can be evaluated later.

This is something I'd actually been thinking about as I think it'd enable the implementation of parameterised fixtures.
