### ISSUE TITLE
Configurable test file name patterns

### ISSUE THREAD

**Issue by silverwind** [darrenburns/ward#173]
Coming from JavaScript, I prefer to use `module.test.py` to test `module.py` but it seems such a filename is not supported:

```` bash
$ ward --path module.test.py
Ward 0.48.0b0, CPython 3.8.5
Collected 0 tests and 0 fixtures in 0.00 seconds.
NO_TESTS_FOUND in 0.00 seconds
````

Maybe you can let the user specify a glob or regexp pattern in `pyproject.toml` used to match test files, similar to jest's [testMatch](https://jestjs.io/docs/en/configuration#testmatch-arraystring) option?

**Comment by darrenburns** [comment]
Python module names can't contain a `.`, as it would prevent it from being imported (since namespacing syntax uses a `.` and it conflicts). I'm going to close this issue for now as I think it makes this issue redundant, but if there's another use case for configurable test file name patterns feel free to reopen and let me know!

**Comment by silverwind** [comment]
In that case maybe you want to consider allowing `module_test.py`. Especially in large directories, I find it very convenient to have test files sorted right after the the tested file.

**Comment by darrenburns** [comment]
@silverwind That is enabled by default, Ward will collect test modules starting with `test_` or ending with `_test` e.g:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/5740731/111800522-f24c0280-88c3-11eb-98c7-7db61bfaf2b1.png">
