### ISSUE TITLE
No pretty failure message for `in` statements

### ISSUE THREAD

**Issue by JoshKarpel** [darrenburns/ward#240]
Working on tests for #233 and noticed that `in` statements don't seem to be getting rewritten to produce pretty output. Minimal example:
```python
@test("assert in not working?")
def _():
    assert "foo" in "bar"
```

```
─────────────────────────────────────────────── assert in not working? ───────────────────────────────────────────────

  Failed at tests/test_terminal.py:300

      298 @test("assert in not working?")
      299 def _():
    ❱ 300     assert "foo" in "bar"
      301

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by darrenburns** [comment]
We only print pretty output for the `==` operator: https://github.com/darrenburns/ward/blob/3bc5de8cf62c6e815bbda165f5b3a3a64d9090af/ward/_terminal.py#L683

If we wanted to print special output for the `in` case, we could add it to the above block of code.

It's not as clear _what_ we'd print in that case, since a diff won't make sense for anything other than equality checks.

**Comment by JoshKarpel** [comment]
Ah, gotcha... I will see if I can come up with anything nice :)
