### ISSUE TITLE
Handling tests that fork: see only one process as a tests

### ISSUE THREAD

**Issue by drakes00** [darrenburns/ward#65]
Hi,

Very nice piece of software! :-)
I was playing with tests including a call to fork and behavior seems a bit strange to me.

# Minimal working example

```python
@test("My test that forks")
def test_minimalFork():
        import time
        fatherPid = os.getpid()
        pid = os.fork()
        if pid == 0:
            # Do stuff
            time.sleep(1)
            import signal
            os.kill(fatherPid, signal.SIGINT)
            expect(True).equals(True)
        else:
            # Do stuff that hangs
            time.sleep(20)
            expect(False).equals(True)
```

# Observed behavior

```
% ward --search Fork
Ward collected 1 tests in 0.17 seconds.


[WARD] Run cancelled - results for tests that ran shown below.

NO_TESTS_FOUND in 1.18 seconds
 PASS  test_SSH:69: My test that forks                                                                                                                                                        

..............................................................................................................................................................................................
 
SUCCESS in 1.24 seconds [ 1 passed ]
```

Given output, it seems that fork is handled as being two different tests (or two instances of ward?).
Obviously, tests running in child process (testing `True == True`) passes and test in father process (testing `False == True`) does not raises and thus is correctly killed by child process.

# Expected behavior (wished behavior)

Only get the pass verdict and not the "NO_TEST_FOUND" and "Run cancelled".

# Conclusion

First, if there a "good" way to kill the process according to ward?
If not, is there a way to specify in the killed process that ward shouldn't look for a test here (thus we only get the pass verdict and not the "NO_TEST_FOUND" and "Run cancelled"?

I'd by happy to contribute if needed ;-)
Cheers

**Comment by darrenburns** [comment]
Perhaps I'm misunderstanding but the observed behaviour is what I would expect.

Here's the output explained line by line, from my understanding:

The parent Ward process collects the 1 test:
```
Ward collected 1 tests in 0.17 seconds.
```

The fork now happens, meaning there are now two Python processes running Ward, and both parent and child processes refer to the same single test.

The SIGINT is received by the parent process, which cancels the run in that process only. When this happens, the parent process prints the following message to the terminal:
```
[WARD] Run cancelled - results for tests that ran shown below.

NO_TESTS_FOUND in 1.18 seconds
```

(The NO_TESTS_FOUND message should probably be NO_TESTS_RUN, because in this case the test *was* found, but was cancelled before it was run).

The child process is still running at this point, and execution enters the `if pid == 0` block, eventually hitting `expect(True).equals(True)`, which results in a passing test. In turn, the child process prints:

```
 PASS  test_SSH:69: My test that forks                                                                                                                                                        

..............................................................................................................................................................................................
 
SUCCESS in 1.24 seconds [ 1 passed ]
```

Note that the parent process exits with a non-zero exit code, because from its perspective no tests were run.

I also performed the same test using `pytest` and got the same outcome:

![image](https://user-images.githubusercontent.com/5740731/72525118-5952cf00-385b-11ea-95c5-e9fee4b0758b.png)

Do you have a specific use-case for using `os.fork` in a test?

**Comment by drakes00** [comment]
I agree that the behavior seems rational given the fork.
I wish I could tell ward to only treat one of the processes in order to only have the right output.
One solution I just though may be to change SIGINT to SIGKILL in order to stop the father's ward. Yet, it feels quite dirty.

The point of the forked test was to run some kind of ```sockerserver.TCPServer().server_forever()``` and in parallel, make GET requests. I managed to avoid the fork with some refactoring.

Thanks

**Comment by darrenburns** [comment]
Glad to hear you managed to sort it.

I don't know what approach you've taken, but for that sort of thing, I'd recommend defining a fixture that starts the server in a separate process (look at multiprocessing module), and tears it down after.

The Teardown Code section of the following page may be useful: https://wardpy.com/guide/fixtures
