### ISSUE TITLE
Recording individual test durations

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#87]
It can be useful to record the durations of individual tests in order to find identify those which are slow.

Pytest has the `--durations=N` option, which will print the N slowest tests. It records the time taken to the fixtures a test depends on too.

**Comment by CodeMouse92** [comment]
You know, if you implemented this, a corollary feature is that you could raise an alert when a test runs *longer than usual*.

**Comment by onlyanegg** [comment]
Hey, @darrenburns. Have you thought about how to do this? I opened a PR with some initial thoughts about how this might work.

I thought it would be better to move the test exception logic to within the Test `__call__` function itself. This abstraction made more sense to me and allows the control of the timer to be within the Test class instead of within the suite. It also creates a circular reference from Test -> TestResult -> Test, which I don't love.

Let me know what you think.

**Comment by onlyanegg** [comment]
After playing around with this, I'm wondering if this is useful. As it is, you could get output like the following:

```
$ ward --duration 3
...
Longest Running Tests

0.00 sec test_suite:341: Suite.generate_test_runs correctly tears down module scoped parameterised tests
0.00 sec test_suite:31: Suite.generate_test_runs generates 5 when suite has 5 tests
0.00 sec test_suite:84: Suite.generate_test_runs fixture teardown code is ran in the expected order
...
```

Would it be more useful to display tests that ran for longer than x seconds? Or maybe display the longest 3, but only if they take longer than x seconds? It might even be cool to kill a test if it takes longer than x seconds, but I think we'd need a second thread / process for that, so it's a bit more of an undertaking.
